/** Website 分类配置 */
const WEBSITE_SORTS: WebsiteSort[] = [
  {
    title: "🚀 入门上手",
    emoji: "🚀",
    sites: [
      {
        title: "ColabFold 快速入门",
        description: "一键运行蛋白质结构预测，零配置上手",
        url: "https://colab.research.google.com/github/sokrypton/ColabFold/blob/main/AlphaFold2.ipynb",
        icon: "",
        color: "#22C55E",
        emoji: "☁️",
        tags: ["Colab", "蛋白质", "教程"],
        isHot: true,
      },
      {
        title: "AlphaFold3 Nature 论文",
        description: "DeepMind 官方发布，预测蛋白质-配体-核酸复合物",
        url: "https://www.nature.com/articles/s41586-024-07487-w",
        icon: "",
        color: "#A855F7",
        emoji: "📄",
        tags: ["论文", "AlphaFold"],
        isNew: true,
      },
      {
        title: "EBI AlphaFold 培训课程",
        description: "欧洲生物信息学研究所官方教程，权威系统",
        url: "https://www.ebi.ac.uk/training/online/courses/alphafold/",
        icon: "",
        color: "#3B82F6",
        emoji: "🎓",
        tags: ["教程", "AlphaFold", "官方"],
        isHot: true,
      },
      {
        title: "Coursera 生物信息学专项课",
        description: "UCSD 出品，7 门课系统学习生信",
        url: "https://www.coursera.org/specializations/bioinformatics",
        icon: "",
        color: "#F59E0B",
        emoji: "🎓",
        tags: ["课程", "生信"],
      },
      {
        title: "DeepChem 官方教程",
        description: "分子机器学习开源库，从入门到实战",
        url: "https://deepchem.io/tutorials/",
        icon: "",
        color: "#10B981",
        emoji: "🧪",
        tags: ["教程", "分子", "机器学习"],
      },
      {
        title: "scGPT 官方文档",
        description: "单细胞大模型使用指南，详细易懂",
        url: "https://scgpt.readthedocs.io/en/latest/",
        icon: "",
        color: "#EC4899",
        emoji: "📖",
        tags: ["文档", "单细胞", "大模型"],
        isNew: true,
      },
      {
        title: "arXiv q-bio 最新论文",
        description: "定量生物学预印本，追踪前沿研究",
        url: "https://arxiv.org/list/q-bio/recent",
        icon: "",
        color: "#DC2626",
        emoji: "📚",
        tags: ["论文", "预印本"],
      },
      {
        title: "B站 - 生物信息学入门",
        description: "国内优质生信入门视频合集",
        url: "https://search.bilibili.com/all?keyword=%E7%94%9F%E7%89%A9%E4%BF%A1%E6%81%AF%E5%AD%A6%E5%85%A5%E9%97%A8",
        icon: "",
        color: "#00A1D6",
        emoji: "📺",
        tags: ["视频", "入门", "国内"],
      },
      {
        title: "知乎 - AI 制药专栏",
        description: "中文 AI 制药科普，深度好文",
        url: "https://www.zhihu.com/topic/21273409/hot",
        icon: "",
        color: "#0084FF",
        emoji: "📝",
        tags: ["科普", "AI制药", "国内"],
      },
      {
        title: "ColabFold GitHub",
        description: "蛋白质折叠开源项目，支持多种模型",
        url: "https://github.com/sokrypton/ColabFold",
        icon: "",
        color: "#6366F1",
        emoji: "💻",
        tags: ["开源", "蛋白质", "GitHub"],
        isHot: true,
      },
    ],
  },
  {
    title: "🛠️ 工具与平台",
    emoji: "🛠️",
    sites: [
      {
        title: "AlphaFold Server",
        description: "DeepMind 官方，支持 AlphaFold3，一键预测",
        url: "https://alphafoldserver.com/",
        icon: "",
        color: "#22C55E",
        emoji: "🧬",
        tags: ["蛋白质", "在线工具", "官方"],
        isHot: true,
      },
      {
        title: "ESMFold",
        description: "Meta AI 出品，速度超快的结构预测",
        url: "https://esmatlas.com/resources?action=fold",
        icon: "",
        color: "#3B82F6",
        emoji: "⚡",
        tags: ["蛋白质", "在线工具"],
        isHot: true,
      },
      {
        title: "ColabFold",
        description: "社区维护，功能最强的云端蛋白质折叠",
        url: "https://github.com/sokrypton/ColabFold",
        icon: "",
        color: "#F59E0B",
        emoji: "☁️",
        tags: ["蛋白质", "开源", "Colab"],
        isHot: true,
      },
      {
        title: "DiffDock",
        description: "扩散模型做分子对接，SOTA 级别",
        url: "https://github.com/gcorso/DiffDock",
        icon: "",
        color: "#A855F7",
        emoji: "🧪",
        tags: ["分子对接", "开源"],
      },
      {
        title: "DiffDock Web Demo",
        description: "Hugging Face 在线体验，无需安装",
        url: "https://huggingface.co/spaces/reginabarzilaygroup/DiffDock-Web",
        icon: "",
        color: "#FBBF24",
        emoji: "🌐",
        tags: ["分子对接", "在线工具"],
        isNew: true,
      },
      {
        title: "scGPT",
        description: "单细胞数据的基础大模型",
        url: "https://github.com/bowang-lab/scGPT",
        icon: "",
        color: "#EC4899",
        emoji: "🧬",
        tags: ["单细胞", "大模型", "开源"],
        isNew: true,
      },
      {
        title: "BioGPT",
        description: "微软生物医学领域预训练语言模型",
        url: "https://github.com/microsoft/BioGPT",
        icon: "",
        color: "#0EA5E9",
        emoji: "🧠",
        tags: ["NLP", "大模型", "开源"],
      },
      {
        title: "BioGPT Hugging Face",
        description: "在线使用 BioGPT，即开即用",
        url: "https://huggingface.co/microsoft/biogpt",
        icon: "",
        color: "#FF6F00",
        emoji: "🤗",
        tags: ["NLP", "在线工具"],
      },
      {
        title: "Hugging Face Bio Models",
        description: "一站式生物 AI 模型库，海量选择",
        url: "https://huggingface.co/models?other=biology",
        icon: "",
        color: "#FBBF24",
        emoji: "🗂️",
        tags: ["模型库", "平台"],
      },
      {
        title: "BiomedCLIP",
        description: "生物医学图像-文本多模态模型",
        url: "https://huggingface.co/microsoft/BiomedCLIP-PubMedBERT_256-vit_base_patch16_224",
        icon: "",
        color: "#10B981",
        emoji: "🖼️",
        tags: ["医学影像", "多模态"],
        isNew: true,
      },
      {
        title: "RoseTTAFold2 Colab",
        description: "Baker Lab 蛋白质预测，另一大流派",
        url: "https://colab.research.google.com/github/sokrypton/ColabFold/blob/main/RoseTTAFold2.ipynb",
        icon: "",
        color: "#DC2626",
        emoji: "🌹",
        tags: ["蛋白质", "Colab"],
      },
      {
        title: "Boltz-1 Colab",
        description: "新一代蛋白质预测工具，值得关注",
        url: "https://colab.research.google.com/github/sokrypton/ColabFold/blob/main/Boltz1.ipynb",
        icon: "",
        color: "#7C3AED",
        emoji: "⚡",
        tags: ["蛋白质", "Colab"],
        isNew: true,
      },
      {
        title: "LocalColabFold",
        description: "本地运行 ColabFold，不怕断网",
        url: "https://github.com/YoshitakaMo/localcolabfold",
        icon: "",
        color: "#6366F1",
        emoji: "💻",
        tags: ["蛋白质", "本地部署"],
      },
      {
        title: "Uni-Fold (国内镜像)",
        description: "深势科技开源，国内访问友好",
        url: "https://github.com/dptech-corp/Uni-Fold",
        icon: "",
        color: "#059669",
        emoji: "🇨🇳",
        tags: ["蛋白质", "国内", "开源"],
      },
      {
        title: "PaddleHelix",
        description: "百度飞桨生物计算平台，国产之光",
        url: "https://github.com/PaddlePaddle/PaddleHelix",
        icon: "",
        color: "#2563EB",
        emoji: "🚀",
        tags: ["生物计算", "国内", "开源"],
      },
      {
        title: "ModelScope 生物模型",
        description: "阿里魔搭社区生物 AI 模型，国内镜像",
        url: "https://modelscope.cn/models?Tasks=life-science",
        icon: "",
        color: "#FF6A00",
        emoji: "🪄",
        tags: ["模型库", "国内"],
      },
    ],
  },
  {
    title: "📚 论文与数据",
    emoji: "📚",
    sites: [
      {
        title: "bioRxiv",
        description: "生物学预印本，抢先看最新研究",
        url: "https://www.biorxiv.org/",
        icon: "",
        color: "#DC2626",
        emoji: "📄",
        tags: ["预印本", "论文"],
      },
      {
        title: "medRxiv",
        description: "医学健康预印本，临床研究必看",
        url: "https://www.medrxiv.org/",
        icon: "",
        color: "#F97316",
        emoji: "🏥",
        tags: ["预印本", "医学"],
      },
      {
        title: "PubMed",
        description: "生物医学文献检索必备",
        url: "https://pubmed.ncbi.nlm.nih.gov/",
        icon: "",
        color: "#2563EB",
        emoji: "📚",
        tags: ["论文库", "检索"],
      },
      {
        title: "PubMed Central (PMC)",
        description: "免费全文数据库，开放获取",
        url: "https://www.ncbi.nlm.nih.gov/pmc/",
        icon: "",
        color: "#0EA5E9",
        emoji: "📖",
        tags: ["论文库", "免费"],
      },
      {
        title: "UniProt",
        description: "蛋白质序列与功能数据库",
        url: "https://www.uniprot.org/",
        icon: "",
        color: "#059669",
        emoji: "🧬",
        tags: ["数据库", "蛋白质"],
      },
      {
        title: "PDB (RCSB)",
        description: "蛋白质 3D 结构数据库",
        url: "https://www.rcsb.org/",
        icon: "",
        color: "#7C3AED",
        emoji: "📦",
        tags: ["数据库", "结构"],
      },
      {
        title: "AlphaFold Database",
        description: "预计算蛋白质结构库，2 亿+ 结构",
        url: "https://alphafold.ebi.ac.uk/",
        icon: "",
        color: "#22C55E",
        emoji: "🧬",
        tags: ["数据库", "蛋白质", "AlphaFold"],
        isHot: true,
      },
      {
        title: "ESM Atlas",
        description: "6 亿+ 蛋白质结构，Meta AI 出品",
        url: "https://esmatlas.com/",
        icon: "",
        color: "#3B82F6",
        emoji: "🗺️",
        tags: ["数据库", "蛋白质"],
        isHot: true,
      },
      {
        title: "Papers With Code - Bio",
        description: "论文 + 代码 + 排行榜，一站搞定",
        url: "https://paperswithcode.com/area/biology",
        icon: "",
        color: "#0891B2",
        emoji: "💻",
        tags: ["论文", "代码", "Benchmark"],
        isHot: true,
      },
      {
        title: "GDC 癌症数据门户",
        description: "TCGA 等癌症基因组数据，研究必备",
        url: "https://portal.gdc.cancer.gov/",
        icon: "",
        color: "#DC2626",
        emoji: "🔬",
        tags: ["数据库", "癌症", "基因组"],
      },
      {
        title: "NCBI GEO",
        description: "基因表达数据库，海量芯片/测序数据",
        url: "https://www.ncbi.nlm.nih.gov/geo/",
        icon: "",
        color: "#6366F1",
        emoji: "📊",
        tags: ["数据库", "基因表达"],
      },
      {
        title: "CASP",
        description: "蛋白质结构预测竞赛，看看谁最强",
        url: "https://predictioncenter.org/",
        icon: "",
        color: "#F59E0B",
        emoji: "🏆",
        tags: ["竞赛", "Benchmark"],
      },
      {
        title: "MoleculeNet",
        description: "分子机器学习 Benchmark 集合",
        url: "https://moleculenet.org/",
        icon: "",
        color: "#10B981",
        emoji: "🧪",
        tags: ["Benchmark", "分子"],
      },
      {
        title: "ClinVar",
        description: "临床变异数据库，疾病关联必查",
        url: "https://www.ncbi.nlm.nih.gov/clinvar/",
        icon: "",
        color: "#EC4899",
        emoji: "🧬",
        tags: ["数据库", "临床", "变异"],
      },
      {
        title: "DrugBank",
        description: "药物数据库，药物-靶点信息全",
        url: "https://go.drugbank.com/",
        icon: "",
        color: "#A855F7",
        emoji: "💊",
        tags: ["数据库", "药物"],
      },
      {
        title: "ChEMBL",
        description: "生物活性小分子数据库，EMBL 出品",
        url: "https://www.ebi.ac.uk/chembl/",
        icon: "",
        color: "#0EA5E9",
        emoji: "⚗️",
        tags: ["数据库", "小分子"],
      },
      {
        title: "知网 - 生物医学",
        description: "国内学术文献检索，中文论文必备",
        url: "https://www.cnki.net/",
        icon: "",
        color: "#DC2626",
        emoji: "🇨🇳",
        tags: ["论文库", "国内"],
      },
      {
        title: "万方数据",
        description: "国内学术资源平台，中文期刊论文",
        url: "https://www.wanfangdata.com.cn/",
        icon: "",
        color: "#2563EB",
        emoji: "📚",
        tags: ["论文库", "国内"],
      },
    ],
  },
  {
    title: "💡 实战案例",
    emoji: "💡",
    sites: [
      {
        title: "Kaggle 生物类竞赛",
        description: "边打比赛边学习，还能拿奖金",
        url: "https://www.kaggle.com/competitions?hostSegmentIdFilter=5",
        icon: "",
        color: "#20BEFF",
        emoji: "🏆",
        tags: ["竞赛", "实战"],
        isHot: true,
      },
      {
        title: "ColabFold AlphaFold2 教程",
        description: "社区维护版本，功能最强大",
        url: "https://colab.research.google.com/github/sokrypton/ColabFold/blob/main/AlphaFold2.ipynb",
        icon: "",
        color: "#F59E0B",
        emoji: "☁️",
        tags: ["教程", "Colab", "蛋白质"],
        isHot: true,
      },
      {
        title: "scGPT 零样本教程",
        description: "单细胞分析零样本应用，官方示例",
        url: "https://github.com/bowang-lab/scGPT/tree/main/tutorials",
        icon: "",
        color: "#EC4899",
        emoji: "🧬",
        tags: ["教程", "单细胞"],
        isNew: true,
      },
      {
        title: "DiffDock 复现指南",
        description: "分子对接实战，从安装到运行",
        url: "https://github.com/gcorso/DiffDock#running-diffdock-on-your-own-complexes",
        icon: "",
        color: "#A855F7",
        emoji: "🧪",
        tags: ["教程", "分子对接"],
      },
      {
        title: "DeepChem 实践案例",
        description: "分子机器学习案例合集，边学边做",
        url: "https://github.com/deepchem/deepchem/tree/master/examples",
        icon: "",
        color: "#10B981",
        emoji: "💻",
        tags: ["教程", "分子", "机器学习"],
      },
      {
        title: "AlphaFold3 输入制作",
        description: "从 FASTA 到 JSON，官方教程",
        url: "https://github.com/google-deepmind/alphafold3/blob/main/docs/input.md",
        icon: "",
        color: "#22C55E",
        emoji: "📝",
        tags: ["教程", "AlphaFold"],
        isNew: true,
      },
      {
        title: "Superbio scGPT App",
        description: "在线运行 scGPT，无需代码",
        url: "https://app.superbio.ai/apps/274",
        icon: "",
        color: "#6366F1",
        emoji: "🌐",
        tags: ["在线工具", "单细胞"],
      },
      {
        title: "天池 AI 制药竞赛",
        description: "阿里云竞赛平台，国内用户友好",
        url: "https://tianchi.aliyun.com/competition/activeList",
        icon: "",
        color: "#FF6A00",
        emoji: "🏅",
        tags: ["竞赛", "国内"],
      },
      {
        title: "和鲸社区 - 生物医学",
        description: "国内数据科学社区，中文教程多",
        url: "https://www.heywhale.com/home/competition",
        icon: "",
        color: "#0EA5E9",
        emoji: "🐳",
        tags: ["社区", "国内", "竞赛"],
      },
      {
        title: "ColabFold 视频教程",
        description: "Boston 蛋白质设计俱乐部出品",
        url: "https://www.youtube.com/watch?v=Rfw7thgGTwI",
        icon: "",
        color: "#DC2626",
        emoji: "📺",
        tags: ["视频", "教程"],
      },
      {
        title: "ESMFold 使用指南",
        description: "Meta AI 官方文档，快速上手",
        url: "https://github.com/facebookresearch/esm#esmfold",
        icon: "",
        color: "#3B82F6",
        emoji: "📖",
        tags: ["教程", "蛋白质"],
      },
      {
        title: "Awesome AI Drug Discovery",
        description: "AI 制药资源汇总，GitHub 热门",
        url: "https://github.com/dengjianyuan/Survey_AI_Drug_Discovery",
        icon: "",
        color: "#7C3AED",
        emoji: "⭐",
        tags: ["资源汇总", "AI制药"],
        isHot: true,
      },
    ],
  },
  {
    title: "💼 从业与变现",
    emoji: "💼",
    sites: [
      {
        title: "BioSpace",
        description: "全球生物医药行业招聘平台",
        url: "https://www.biospace.com/",
        icon: "",
        color: "#6366F1",
        emoji: "🌐",
        tags: ["招聘", "求职", "国际"],
      },
      {
        title: "LinkedIn 计算生物学职位",
        description: "搜索全球计算生物学岗位",
        url: "https://www.linkedin.com/jobs/search/?keywords=computational%20biology",
        icon: "",
        color: "#0A66C2",
        emoji: "💼",
        tags: ["招聘", "求职"],
        isHot: true,
      },
      {
        title: "丁香人才",
        description: "国内生物医药招聘第一站",
        url: "https://www.jobmd.cn/",
        icon: "",
        color: "#22C55E",
        emoji: "🇨🇳",
        tags: ["招聘", "国内"],
        isHot: true,
      },
      {
        title: "AI 制药公司列表",
        description: "全球 AI 制药公司汇总，持续更新",
        url: "https://github.com/dengjianyuan/Survey_AI_Drug_Discovery#companies",
        icon: "",
        color: "#A855F7",
        emoji: "🏢",
        tags: ["公司", "AI制药"],
      },
      {
        title: "Indeed AI 制药岗位",
        description: "AI Drug Discovery 相关职位",
        url: "https://www.indeed.com/jobs?q=ai+drug+discovery",
        icon: "",
        color: "#2164F3",
        emoji: "🔍",
        tags: ["招聘", "AI制药"],
      },
      {
        title: "BOSS 直聘 - 生物AI",
        description: "国内招聘平台，生物AI岗位",
        url: "https://www.zhipin.com/web/geek/job?query=%E7%94%9F%E7%89%A9AI",
        icon: "",
        color: "#00BEAB",
        emoji: "🤝",
        tags: ["招聘", "国内"],
      },
      {
        title: "猎聘 - AI制药",
        description: "高端人才招聘，AI制药方向",
        url: "https://www.liepin.com/zhaopin/?key=AI%E5%88%B6%E8%8D%AF",
        icon: "",
        color: "#FF5722",
        emoji: "🎯",
        tags: ["招聘", "国内"],
      },
      {
        title: "CB Insights AI 制药报告",
        description: "行业趋势分析，市场研究必读",
        url: "https://www.cbinsights.com/research/ai-in-drug-discovery/",
        icon: "",
        color: "#1E3A5F",
        emoji: "📊",
        tags: ["报告", "行业分析"],
      },
      {
        title: "Nature Reviews Drug Discovery",
        description: "药物发现顶刊，了解行业前沿",
        url: "https://www.nature.com/nrd/",
        icon: "",
        color: "#DC2626",
        emoji: "📰",
        tags: ["期刊", "行业"],
      },
      {
        title: "DeepTech - AI 制药",
        description: "中文科技媒体，AI制药报道",
        url: "https://www.deeptechchina.com/category/ai-drug",
        icon: "",
        color: "#000000",
        emoji: "📱",
        tags: ["媒体", "国内"],
        isNew: true,
      },
      {
        title: "医药魔方",
        description: "医药行业情报平台，数据驱动",
        url: "https://www.pharmcube.com/",
        icon: "",
        color: "#3B82F6",
        emoji: "💎",
        tags: ["平台", "国内", "行业"],
      },
      {
        title: "知识星球 - 生信技能树",
        description: "国内生信付费社群，干货满满",
        url: "https://wx.zsxq.com/dweb2/index/group/88885885545828",
        icon: "",
        color: "#F59E0B",
        emoji: "⭐",
        tags: ["社群", "付费", "国内"],
      },
    ],
  },
  {
    title: "🔗 友链与社区",
    emoji: "🔗",
    sites: [
      {
        title: "ColabFold Discord",
        description: "蛋白质折叠社区，大佬云集",
        url: "https://discord.gg/gna8maru7d",
        icon: "",
        color: "#5865F2",
        emoji: "💬",
        tags: ["社群", "Discord"],
        isHot: true,
      },
      {
        title: "Hugging Face",
        description: "AI 模型社区，生物模型专区",
        url: "https://huggingface.co/",
        icon: "",
        color: "#FF6F00",
        emoji: "🤗",
        tags: ["社区", "模型"],
      },
      {
        title: "BioStars",
        description: "生物信息学问答社区，有问必答",
        url: "https://www.biostars.org/",
        icon: "",
        color: "#22C55E",
        emoji: "⭐",
        tags: ["社区", "问答"],
        isHot: true,
      },
      {
        title: "Reddit r/bioinformatics",
        description: "生信讨论区，英文社区",
        url: "https://www.reddit.com/r/bioinformatics/",
        icon: "",
        color: "#FF4500",
        emoji: "🔥",
        tags: ["社区", "Reddit"],
      },
      {
        title: "Reddit r/computationalbiology",
        description: "计算生物学讨论区",
        url: "https://www.reddit.com/r/computationalbiology/",
        icon: "",
        color: "#FF4500",
        emoji: "🧬",
        tags: ["社区", "Reddit"],
      },
      {
        title: "SEQanswers",
        description: "测序技术论坛，NGS 专家社区",
        url: "http://seqanswers.com/",
        icon: "",
        color: "#3B82F6",
        emoji: "🧪",
        tags: ["社区", "测序"],
      },
      {
        title: "GitHub Topics: Computational Biology",
        description: "计算生物学开源项目汇总",
        url: "https://github.com/topics/computational-biology",
        icon: "",
        color: "#6366F1",
        emoji: "💻",
        tags: ["GitHub", "开源"],
      },
      {
        title: "生信技能树",
        description: "国内生信学习社区，资源超多",
        url: "https://www.biotrainee.com/",
        icon: "",
        color: "#22C55E",
        emoji: "🌳",
        tags: ["社区", "学习", "国内"],
      },
      {
        title: "生信菜鸟团",
        description: "公众号/知乎，中文生信科普",
        url: "https://www.zhihu.com/people/bioinfo-rookie",
        icon: "",
        color: "#0084FF",
        emoji: "🐣",
        tags: ["公众号", "国内"],
      },
      {
        title: "DrugAI",
        description: "AI 制药公众号，行业资讯",
        url: "https://www.zhihu.com/column/drugai",
        icon: "",
        color: "#A855F7",
        emoji: "💊",
        tags: ["公众号", "AI制药", "国内"],
        isNew: true,
      },
      {
        title: "Inside UniProt Blog",
        description: "UniProt 官方博客，数据库动态",
        url: "https://insideuniprot.blogspot.com/",
        icon: "",
        color: "#059669",
        emoji: "📝",
        tags: ["博客", "官方"],
      },
      {
        title: "EMBL-EBI Training",
        description: "欧洲生信研究所培训资源",
        url: "https://www.ebi.ac.uk/training/",
        icon: "",
        color: "#2563EB",
        emoji: "🎓",
        tags: ["培训", "官方"],
      },
      {
        title: "科学网 - 生物信息",
        description: "国内学术社区，生信板块",
        url: "https://blog.sciencenet.cn/?bioinformatics",
        icon: "",
        color: "#DC2626",
        emoji: "🔬",
        tags: ["社区", "国内"],
      },
      {
        title: "小木虫 - 生物信息",
        description: "国内学术论坛，生信版块",
        url: "https://muchong.com/bbs/forumdisplay.php?fid=210",
        icon: "",
        color: "#F59E0B",
        emoji: "🐛",
        tags: ["论坛", "国内"],
      },
    ],
  },
];

/** 专题/合集配置 */
const TOPICS: TopicItem[] = [
  {
    title: "AlphaFold 全家桶",
    description: "从入门到进阶，蛋白质结构预测一网打尽",
    emoji: "🧬",
    color: "#22C55E",
    urls: [
      "https://alphafoldserver.com/",
      "https://alphafold.ebi.ac.uk/",
      "https://colab.research.google.com/github/sokrypton/ColabFold/blob/main/AlphaFold2.ipynb",
      "https://www.ebi.ac.uk/training/online/courses/alphafold/",
      "https://www.nature.com/articles/s41586-024-07487-w",
    ],
  },
  {
    title: "AI 制药入门包",
    description: "零基础入坑 AI 制药，这些就够了",
    emoji: "💊",
    color: "#A855F7",
    urls: [
      "https://deepchem.io/tutorials/",
      "https://github.com/gcorso/DiffDock",
      "https://www.coursera.org/specializations/bioinformatics",
      "https://github.com/dengjianyuan/Survey_AI_Drug_Discovery",
      "https://moleculenet.org/",
    ],
  },
  {
    title: "大模型速查",
    description: "生物领域大模型合集，按需取用",
    emoji: "🤖",
    color: "#3B82F6",
    urls: [
      "https://github.com/bowang-lab/scGPT",
      "https://github.com/microsoft/BioGPT",
      "https://huggingface.co/models?other=biology",
      "https://huggingface.co/microsoft/biogpt",
      "https://github.com/facebookresearch/esm",
    ],
  },
  {
    title: "蛋白质工具箱",
    description: "结构预测、折叠、对接工具大全",
    emoji: "🔧",
    color: "#F59E0B",
    urls: [
      "https://alphafoldserver.com/",
      "https://esmatlas.com/resources?action=fold",
      "https://github.com/sokrypton/ColabFold",
      "https://github.com/gcorso/DiffDock",
      "https://colab.research.google.com/github/sokrypton/ColabFold/blob/main/RoseTTAFold2.ipynb",
    ],
  },
  {
    title: "数据库合集",
    description: "蛋白质、基因、药物数据库一站式入口",
    emoji: "📦",
    color: "#0EA5E9",
    urls: [
      "https://www.uniprot.org/",
      "https://www.rcsb.org/",
      "https://alphafold.ebi.ac.uk/",
      "https://esmatlas.com/",
      "https://go.drugbank.com/",
      "https://www.ebi.ac.uk/chembl/",
    ],
  },
];

/** Website 配置（2023.3.29 已废弃） */
const WEBSITE_ITEMS: WebsiteItem[] = [];

const GLOBAL_CONFIG = {
  /**
   * 站点名称
   */
  BLOG_NAME: "BioAI 导航",
  /**
   * 站点副标题
   */
  SITE_SUBTITLE: "生命科学 × 生成式 AI 的一站式资源入口",
  /**
   * 主站链接（点击 Logo 跳转）
   */
  BLOG_URL: "#",
  /**
   * 指定中心 LOGO 图片地址
   */
  LOGO_URL: null,
  /**
   * Github 链接
   */
  GITHUB_URL: "https://github.com/your-repo/bioai-nav",
  /**
   * 背景图片地址
   */
  BACKGROUND_IMG_URL: "https://api.dujin.org/bing/1920.php",
  /**
   * ICP 备案号，留空不显示
   */
  ICP: "",
  ICP_URL: "https://beian.miit.gov.cn/",
  FOOTER_INFO: true,
  /**
   * 网站欢迎标语（年轻化、口语化）
   */
  SLOGANS: [
    "🧬 AI + 生科，未来已来",
    "🚀 从入门到上手，这里都有",
    "💡 别光收藏，用起来！",
    "🔬 让 AI 帮你做科研",
    "🎯 找工具？找资源？找对地方了",
    "📚 论文太多？先看精选",
    "💼 想入行？先看这里",
    "🤖 GenAI × Bio = ∞",
  ],
  /**
   * Website 分类配置
   */
  WEBSITE_SORTS,
  /**
   * 专题/合集配置
   */
  TOPICS,
  /**
   * Website 配置（2023.3.29 已废弃）
   */
  WEBSITE_ITEMS,
  /**
   * 网站 Title Keywords Description 的配置，用于 SEO
   */
  TKD: {
    title: "BioAI 导航 - AI 生命科学资源站",
    keywords:
      "AI生命科学,生成式AI,AlphaFold,AI制药,生物信息学,蛋白质结构预测,BioGPT,scGPT,AI医药",
    description:
      "BioAI 导航 - 生命科学 × 生成式 AI 的一站式资源入口，收录 AI 制药、蛋白质预测、生物大模型等领域的工具、教程、论文与数据资源。",
  },
  /**
   * 主题色配置
   */
  THEME: {
    primaryColor: "#22C55E", // 基因绿
    secondaryColor: "#3B82F6", // 分子蓝
    accentColor: "#A855F7", // 细胞紫
  },
};

export default GLOBAL_CONFIG;
